### ISSUE TITLE
ClickCommand does not allow CanExecute function

### ISSUE THREAD

**Issue by Depechie** [robinmanuelthiel/flexbutton#11]
When using the FlexButton ClickCommand bound to a Command that has CanExecute, the button will not be disabled when invalid or run the CanExecuteMethod to validate.

Regular button handles this.

**Comment by robinmanuelthiel** [comment]
Yep, nice catch, thanks! Will look after that in the next update!

**Comment by Depechie** [comment]
Done an initial PR for it ( https://github.com/robinmanuelthiel/flexbutton/pull/12 ), but not sure on how to visually show that a button is disabled.
So maybe you can add that and finish the issue :)

**Comment by robinmanuelthiel** [comment]
What would you propose as an "Disabled" indicator? Lower opacity? Different Color? Clearly want to let the Developer choose whats to do but I need a default

**Comment by Depechie** [comment]
Good idea to add extra properties for Devs to override default behaviour!
For default maybe just mimic what regular Xamarin forms button does?

**Comment by Depechie** [comment]
Well on the other hand just changing opacity would be a very good start...

**Comment by robinmanuelthiel** [comment]
I gave it a try in the Demo App and set the Opacity to 0.5 when a button is disabled. Looks quite alright for me. What do you think?

![image](https://user-images.githubusercontent.com/5874465/37967296-9e705e76-31d3-11e8-8d52-127f62c0d176.png)

**Comment by Depechie** [comment]
All in favour raise their hand: +1

;)

**Comment by robinmanuelthiel** [comment]
Fixed in latest 0.5.0 Release
