### ISSUE TITLE
Background Color Wrong?

### ISSUE THREAD

**Issue by Jyosua** [robinmanuelthiel/flexbutton#13]
When I tried using flexbutton to replace some of my existing buttons, I noticed that my chosen background colors were not being rendered the same. I'm using an iPhone X iOS 11.2 simulator, but I also tested it on the iPhone 8 simulator.

My original background color with my buttons was #37404A. This was rendered as #47525C.

The closest I could get was #37404B, but in order to do so, I had to use #2A313A. My XAML is below:

```xml
<flex:FlexButton WidthRequest="40" HeightRequest="40" CornerRadius="5" Padding="0" Margin="5,5,10,10"
                             Icon="chevrondown.png" ForegroundColor="#A8B4BB" HighlightForegroundColor="#A8B4BB"
                             BackgroundColor="#2A313A" HighlightBackgroundColor="#4E5866" TouchedDown="NextButtonPressed" />
```

It looks like the color is being overlayed or transformed in some way. This issue doesn't appear to affect Android; the color that showed up was the color set when I tested it on API 26, but on multiple iOS simulators, the color shows up wrong. Am I doing something wrong here?

**Comment by robinmanuelthiel** [comment]
Mh, could have something to do with Xamarin's `Frame` implementation, that FlexButton relies on. It has a bunch of these bugs and glitches. Will dig into that for the next version!

**Comment by robinmanuelthiel** [comment]
Yep, I can reproduce it. Looks like a Xamarin.Forms bug. I created an issue: https://github.com/xamarin/Xamarin.Forms/issues/2218
