### ISSUE TITLE
Label and icon position configuration

### ISSUE THREAD

**Issue by asmundur** [robinmanuelthiel/flexbutton#15]
Thanks for a great control. 

But I'd like to make a feature request.

Make it possible to control the location of the icon, and the alignment of the textlabel. A second line label would also be great, to allow for two fontsizes.

**Comment by robinmanuelthiel** [comment]
Some of it is already referenced in #9. As we already have a PR for this, this might come in the next release soon!

**Comment by robinmanuelthiel** [comment]
Icon Position is added in latest 0.5.0 Release
