### ISSUE TITLE
Add FontAttributes properties

### ISSUE THREAD

**Issue by DiegoPatrocinio** [robinmanuelthiel/flexbutton#21]
Hi there!

First of all, thank you very much for the amazing work you did, it's indeed a really Flexible button and very helpful!

If possible, I would like to suggest a new feature, which is add the FontAttributes properties for the button text, I think this would make it even more flex!

Thank you once again!

**Comment by robinmanuelthiel** [comment]
Good idea! Will add this to the backlog! Shouldn't be too hard by the way so if you want: PRs are welcome!

**Comment by DiegoPatrocinio** [comment]
Good to know! Indeed, it shouldn't be that hard, I'll try to work on it this weekend and hopefully finish it, then I'll do a PR!

**Comment by stormlion227** [comment]
May I implement this feature now? Because I need this feature asap.

**Comment by stormlion227** [comment]
I've created pull request.

**Comment by robinmanuelthiel** [comment]
Thanks, @stormlion227! Looks very good, I already merged it. Font Attributes, Font Family and Command Parameters will appear in the next update 0.7.0. Again, great work! Thanks a lot!
