### ISSUE TITLE
When border is set and then background color is transparent, It is filled with border color.

### ISSUE THREAD

**Issue by stormlion227** [robinmanuelthiel/flexbutton#22]

**Comment by robinmanuelthiel** [comment]
Yeah, I already realized this when I played around with it in the Demo Project. The problem is, that I don't really draw the Border around the button but as a filled `Frame`behind it. My current workaround is to set the button's background color to the same color as the page's background.

**Comment by robinmanuelthiel** [comment]
What options do we have to fix this:

- Wait for Xamarin.Forms to fix their `Frame.Border` implementation
- Draw a "real" border with custom renderers, like @ASloth suggested in #18 
- Write some logic to detect this scenario and adopt the parent's background color

Anything else?

**Comment by ASloth** [comment]
@robinmanuelthiel ist this the border bug? https://github.com/xamarin/Xamarin.Forms/issues/1347
It should be resolved in .Forms 3.0. You could use the frame.border and the custom drawing only for Android as a temporary workaround until .Forms 3.0 is released.

**Comment by robinmanuelthiel** [comment]
Kindof. That bug only references to the Border that NEVER gets drawn on Android. It is still super unflexible as is does not allow us to set border with...

**Comment by stormlion227** [comment]
Ok. I understand now.
