### ISSUE TITLE
Corner Radius not working. How to fix it?

### ISSUE THREAD

**Issue by moogiis** [robinmanuelthiel/flexbutton#29]
Corner Radius not working. How to fix it?

IOS, Android same

![2018-04-12_02-26-53-](https://user-images.githubusercontent.com/21235622/38659833-ba43a900-3e5d-11e8-9091-83ee947e6bc6.jpg)

**Comment by robinmanuelthiel** [comment]
Xamarin.Forms 2.5.1 issue. Fix is in the works

**Comment by robinmanuelthiel** [comment]
You can update to the 0.7.0-pre for a quick fix

**Comment by moogiis** [comment]
Thank you so much 👍
