### ISSUE TITLE
Change only background color

### ISSUE THREAD

**Issue by a-iafrate** [robinmanuelthiel/flexbutton#34]
Hi
i need to create a coloured button with a colored image, i only need background color is changed and not Highlight color is applied to the image.
I have tried setting various color to transparent but don't work.
How can i do this?

Thanks
Alessio

**Comment by robinmanuelthiel** [comment]
So if I understood you correctly, you only want a button with colored background and colored icon but no change on tap? Then you need to set both `BackgroundColor` and `HighlightBackgroundColor` to the same color! Then nothing changes on highlight!

```xml
<flex:FlexButton
    HorizontalOptions="Center"
    WidthRequest="76"
    HeightRequest="76"
    CornerRadius="38"
    Icon="lightbulb.png"
    BackgroundColor="Red"
    HighlightBackgroundColor="Red"
    ForegroundColor="Blue"
    HighlightForegroundColor="Blue"/>
```

**Comment by a-iafrate** [comment]
Hi,
thanks to your reply.
in your example when pressing the button the background remain the same color and the icon change from white to blue, i need only change the background color and leave icon with it's original color

**Comment by robinmanuelthiel** [comment]
The icon should definitely not change in my example, as I set the `HighlightForegroundColor` (for the icon) to the same as `ForegroundColor`. If you need the background color to change on click, set the `HighlightBackgroundColor` to something else:

  ```xml
<flex:FlexButton
    HorizontalOptions="Center"
    WidthRequest="76"
    HeightRequest="76"
    CornerRadius="38"
    Icon="lightbulb.png"
    BackgroundColor="Red"
    HighlightBackgroundColor="Green"
    ForegroundColor="Blue"
    HighlightForegroundColor="Blue"/>
```

**Comment by robinmanuelthiel** [comment]
Which version of the FlexButton do you use?
Which version of Xamarin.Forms do you use?
Which OS are you talking about?

**Comment by a-iafrate** [comment]
i have tried your code on xamarin forms 2.5 with latest version available on github of Flexbutton code target on android and when i click the button the bulb from white become blue

**Comment by robinmanuelthiel** [comment]
So it is not blue in the beginning? Although `ForegroundColor` is set to `Blue`?

**Comment by robinmanuelthiel** [comment]
Just tried out the exact code and worked for me on Android (Xamarin.Forms 3.0 - should not make a difference) and FlexButton 0.7.0

**Comment by a-iafrate** [comment]
Hi
i have upgrade xamarin forms to 3.0 and now it work, i have only one problem, if i have a colored image on the button how can mantain it's color? if i set ForegroundColor to white it became white and if i set to transparent it's not visible.
