### ISSUE TITLE
Change icon size

### ISSUE THREAD

**Issue by wanderson-ra** [robinmanuelthiel/flexbutton#35]
How can I increase the size of the button icon?

**Comment by robinmanuelthiel** [comment]
You can, by setting the `Padding` property

**Comment by robinmanuelthiel** [comment]
Can you please provide a code sample (and icon) that you used for your tries?

**Comment by MAlexanderRobinson** [comment]
It also isn't working for me. Here is my Code:
`    <flex:FlexButton
                        WidthRequest="90"
                        HeightRequest="90"
                        CornerRadius="45"
                        ForegroundColor="#ffffff"
                        HighlightForegroundColor="#49516F"
                        Icon="ic_add_white.png"
                        BackgroundColor="#03A9F4"
                        HorizontalOptions="Center"
                        VerticalOptions="Center"
                        Padding="0"
                        HasShadow="true"
                        ClickedCommand="{Binding AddButtonClicked}"
                        HighlightBackgroundColor="#80bbff"
                        FontSize="Large"/>`
    <flex:FlexButton
                        WidthRequest="90"
                        HeightRequest="90"
                        CornerRadius="45"
                        ForegroundColor="#ffffff"
                        HighlightForegroundColor="#49516F"
                        Icon="ic_add_white.png"
                        BackgroundColor="#03A9F4"
                        HorizontalOptions="Center"
                        VerticalOptions="Center"
                        Padding="0"
                        HasShadow="true"
                        ClickedCommand="{Binding AddButtonClicked}"
                        HighlightBackgroundColor="#80bbff"
                        FontSize="Large"/>`

![ic_add_white](https://user-images.githubusercontent.com/25991564/50359330-fee52300-0521-11e9-9493-c13c1002db0d.png)
![ic_add_white](https://user-images.githubusercontent.com/25991564/50359310-eecd4380-0521-11e9-93a0-108ec438f173.png)
![ic_add_white](https://user-images.githubusercontent.com/25991564/50359299-df4dfa80-0521-11e9-8c81-fa8284cdd4f5.png)
![ic_add_white](https://user-images.githubusercontent.com/25991564/50359305-e4ab4500-0521-11e9-95de-70ba85157632.png)

I have these from drawable-hdpi to drawable-xxxhdpi

**Comment by MAlexanderRobinson** [comment]
I am getting large icons when deploying to my iOS device and only have one large icon in my resources folder. The icons remain small in android.

**Comment by MiqueiasGFernandes** [comment]
@wanderson-ra , Do you get a solution? I have issue with this, padding are resizing my icons, but are wrapping my text on FlexButton
