### ISSUE TITLE
IsEnabledProperty does not work

### ISSUE THREAD

**Issue by acaliaro** [robinmanuelthiel/flexbutton#36]
Hi.
I have this code

            flexButtonSalva.SetBinding(FlexButton.IsEnabledProperty, "IsSalvaEnabled");

When IsSalvaEnabled is "false", the button is enabled...

If I change IsEnabledProperty with IsVisibleProperty, when IsSalvaEnabled is "false", the button disappear.

So I think there is a problem with Enabled property

Alessandro

**Comment by robinmanuelthiel** [comment]
I tried it an cannot reproduce that behavior. Can you please provide some additional info or (best case) attach a sample project that demonstrates that?

**Comment by acaliaro** [comment]
I am not able to reproduce it. I close… thanks
