### ISSUE TITLE
Differentiate your GestureFrameRenderer with Frame Class

### ISSUE THREAD

**Issue by clovs** [robinmanuelthiel/flexbutton#39]
Hello,

Could be nice if you don't use the Basic Frame Class for your custom renderer.

Because it could make some issue in our code using Frame and custom renderers too

I will think about a PR :)

**Comment by clovs** [comment]
https://github.com/robinmanuelthiel/flexbutton/pull/40

**Comment by robinmanuelthiel** [comment]
Ha! You are absolutely right, thanks for pointing out! Will merge!
