### ISSUE TITLE
Support UWP

### ISSUE THREAD

**Issue by YZahringer** [robinmanuelthiel/flexbutton#4]

**Comment by Goldstrike** [comment]
It would be a good idea!
@robinmanuelthiel do you think that is it easily feasible?

**Comment by robinmanuelthiel** [comment]
Shouldn't be a problem. Will dig into that for the upcoming releases. If you can't want: PRs are welcome :)

**Comment by MarcusSpecht** [comment]
Can't wait to have this in UWP too! Awesome work.

**Comment by Agredo** [comment]
Hello I am using your Awsome Nuget PlugIn! But in UWP the Button does not work. It shows up but it is not possible to click! Am I doing something wrong? 

Awsome Thank you!

**Comment by robinmanuelthiel** [comment]
Hi @Agredo, UWP is not currently supported yet but is in the works. This is why, here is an issue on GitHub that is still marked as `open`. You can also see, that I added it to the 1.0 Release milestone.

**Comment by robinmanuelthiel** [comment]
Overall, I am nearly finished with the UWP implementation, but need some code to change the icon color overlay dynamically. Rest is done. So if someone has code for that...

**Comment by Agredo** [comment]
@robinmanuelthiel Thank you for your answer. How is the icon implemented? As image or by Fontfamily and Content?

**Comment by Agredo** [comment]
Maybe this is helpful? 
https://stackoverflow.com/questions/17208254/how-to-change-pixel-color-of-an-image-in-c-net

**Comment by robinmanuelthiel** [comment]
UWP is here! https://github.com/robinmanuelthiel/flexbutton/releases/tag/v0.8.0
