### ISSUE TITLE
Question about Building derived class from FlexButton

### ISSUE THREAD

**Issue by newdeal30** [robinmanuelthiel/flexbutton#41]
Hi!

I'm trying to build a class that is deriving from FlexButton. 
When the Button is created i get an exception:

Xamarin.Forms.Xaml.XamlParseException: Position 30:18. Type extensions:TouchGestureRecognizer not found in xmlns clr-namespace:Flex.Extensions

In my code i  do something like this:

C#:
[XamlCompilation(XamlCompilationOptions.Compile)]
public partial class MyFlexButton: FlexButton {
  public MyFlexButton() {
    InitializeComponent();
  }
}

Xaml:
<?xml version="1.0" encoding="UTF-8"?>
<flex:FlexButton xmlns="http://xamarin.com/schemas/2014/forms" 
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
	     xmlns:extensions="clr-namespace:Flex.Extensions"
	    xmlns:flex="clr-namespace:Flex.Controls;assembly=Flex"
             x:Class="MyControls.MyFlexButton"/>

Does anybody have a solution for this?
I would like to add properties....

Thanks and regards

**Comment by robinmanuelthiel** [comment]
Is that thread still active? Don't really know how I can help you here. Can you show me the full code with namespaces, please?
