### ISSUE TITLE
[Update] Border Frame on Xamarin.forms 3.0

### ISSUE THREAD

**Issue by clovs** [robinmanuelthiel/flexbutton#44]
Hello,

Xamarin.Forms 3.0 has just been released and they fix the issue on Android with border line frame.

So now we could just use one Frame to make appear the Border of it.
And It could also allow us, to get a button with transparent Background but borderer

Let me know about your expectation,
Regards,

**Comment by IeuanWalker** [comment]
@clovs Does this relate to the fact that all flex buttons in the app now has a white border since I updated to version 3. Or should I create a new issue for it?

**Comment by clovs** [comment]
Yeah, the new Xamarin.Forms 3.0 is making the Frame with border thickness to one on Android by default.

**Comment by IeuanWalker** [comment]
@clovs Ahh thanks for the update. So how would I fix this for my solution, because it's happening for other controls too?

**Comment by clovs** [comment]
I have no time to make a PR for the moment.
But you just have to copy & past to your project this two file from: [the repo](https://github.com/robinmanuelthiel/flexbutton/tree/master/Flex/Controls)
And but BoderColor property of Frames in the Xaml to Color.transparent.

**Comment by robinmanuelthiel** [comment]
Hey guys! I don't think, we can use the Xamarin.Forms 3.0 implementation for Borders right now, as it is still very buggy (https://github.com/xamarin/Xamarin.Forms/issues/2634) and does **not have border thickness**. As the whole concept of this project is flexibility, I think we should stick with our implementation for now.

I will provide a quick-fix for https://github.com/xamarin/Xamarin.Forms/issues/2634 on Android within the next days!

**Comment by clovs** [comment]
Well it looks fine to me, Thanks. :)

**Comment by IeuanWalker** [comment]
@robinmanuelthiel awesome thanks a lot
