### ISSUE TITLE
Support shadow effect

### ISSUE THREAD

**Issue by rraallvv** [robinmanuelthiel/flexbutton#49]
**Describe the solution you'd like**
Not sure if this is already supported but couldn't find a way to add/enable a shadow effect to the button.

**Pull Request**
I could make a PR in case it's not supported yet and I can figure out how to implement it.

**Comment by rraallvv** [comment]
I tried setting `hasShadow="true"` [here](https://github.com/robinmanuelthiel/flexbutton/blob/master/Flex/Controls/FlexButton.xaml#L17) and [here](https://github.com/robinmanuelthiel/flexbutton/blob/master/Flex/Controls/FlexButton.xaml#L33), it doesn't work though.

**Comment by robinmanuelthiel** [comment]
Implemented in version 0.9.0: https://www.nuget.org/packages/Forms.Controls.FlexButton/0.9.0
