### ISSUE TITLE
font size option

### ISSUE THREAD

**Issue by wipflash** [robinmanuelthiel/flexbutton#5]
please, add font size option.

**Comment by robinmanuelthiel** [comment]
Good idea, will do in the next release!

**Comment by robinmanuelthiel** [comment]
We got a nice PR #7 from @yurkinh! Thanks to him I can release a new version soon!

**Comment by wipflash** [comment]
Nice to here that

**Comment by robinmanuelthiel** [comment]
And here we go. FontSize is available in the latest release 0.3.0
https://www.nuget.org/packages/Forms.Controls.FlexButton/
