### ISSUE TITLE
Creating flexbutton from Code Behind has jumping issue

### ISSUE THREAD

**Issue by shaneconaty** [robinmanuelthiel/flexbutton#50]
Hello,

I am having an issue where the width of my button is changing when it is added from the code behind. this is resulting in the last letter of my button being shifted to a second line for a second. 
The button which is added from the XAML is not affected. 
Any help would be hugely appreciated.

Regards,
Shane

XAML
`<StackLayout BackgroundColor="White">
        <ScrollView Orientation="Horizontal"
                    Padding="0">
            <StackLayout Orientation="Horizontal" HeightRequest="50" 
                         Padding="0" BackgroundColor="MidnightBlue"
                         Spacing="0">
                <flex:FlexButton
                    WidthRequest="70"
                    HeightRequest="50"
                    Icon="folder_up.png"
                    Padding="0"
                    HorizontalOptions="Center"
                    ForegroundColor="#ffffff"
                    HighlightForegroundColor="#49516F"
                    BackgroundColor="#6279B8"
                    HighlightBackgroundColor="#8EA4D2"
                    ClickedCommand="{Binding BackUpBtnCommand}"/>
                <StackLayout Orientation="Horizontal" x:Name="TopButtons"
                             Padding="0" Spacing="0">                 
                </StackLayout>
            </StackLayout>
        </ScrollView>`

C#
`private void CreateTopButtons()
        {
            TopButtons.Children.Clear();
            TopButtons.HeightRequest = 50;

            foreach (var bc in ViewModel.BreadCrumbs)
            {
                var butt = new FlexButton
                {
                    Text = bc.Name,
                    WidthRequest = 100,
                    HorizontalOptions = LayoutOptions.Start,
                    ForegroundColor = Color.FromHex("#ffffff"),
                    HighlightForegroundColor = Color.FromHex("#49516F"),
                    BackgroundColor = Color.FromHex("#6279B8"),
                    HighlightBackgroundColor = Color.FromHex("#8EA4D2"),
                    TouchedUpCommand = ViewModel.SetCommand(bc)
                };
                TopButtons.Children.Add(butt);
            }
        }`

(sorry about the huge screenshots)

![image](https://user-images.githubusercontent.com/30483101/41356452-d73e74ce-6f1b-11e8-8aaf-fa36632fb300.png)
![image](https://user-images.githubusercontent.com/30483101/41356563-124c9122-6f1c-11e8-996e-7d1b5557caf1.png)

**Comment by robinmanuelthiel** [comment]
Can you please check, if this is still an issue in v0.9.0? Fixed in version 0.9.0: https://www.nuget.org/packages/Forms.Controls.FlexButton/0.9.0

You can control the max number of lines now, which is `1` by default.
