### ISSUE TITLE
The control FlexButton not work in WUP proyect

### ISSUE THREAD

**Issue by LeonidasMx** [robinmanuelthiel/flexbutton#52]
Hi Every one, I'm been workin with the Flexbutton control over a PLC project, and it wokrs fine in the  Android and iOS projects but not work in UWP project, the project runs ok whiout errors but the button only appears like image, any else have some idea?

Project version netstand 2 and Xamarin Forms 3.0

**Comment by smstuebe** [comment]
maybe already fixed in #51 ? :D

**Comment by LeonidasMx** [comment]
Hi smstuebe, thanks for your answer but not is my case my version of Visual Studio is 15.7.3 and the windows 10 version is the same of the image of the post

**Comment by Amitai5** [comment]
I also have this problem. As @LeonidasMx said it works fine in android and IOS, but in UWP the Flexbutton does not seem to work. The button does not trigger the clicked event once clicked nor does it change the color of the object itself. I have gone ahead and made a new project that just has the button and nothing else. Here are the screenshots of that program:

![partone](https://user-images.githubusercontent.com/8137628/41557032-369696da-72f1-11e8-98f4-94ea8ab6679b.PNG)
![parttwo](https://user-images.githubusercontent.com/8137628/41557034-3926636c-72f1-11e8-875b-9344a93c685c.PNG)
![partthree](https://user-images.githubusercontent.com/8137628/41557039-3abb2172-72f1-11e8-9d16-387658f7ff7e.PNG)

I am using Xamarin Forms 3.0.0.561731 and DotNet-Standard 2. Hope this helps!

**Comment by robinmanuelthiel** [comment]
UWP is currently not officially supported. Still working on that

**Comment by robinmanuelthiel** [comment]
Should be working now with 0.8.0 - https://github.com/robinmanuelthiel/flexbutton/releases/tag/v0.8.0

**Comment by LeonidasMx** [comment]
Hi robinmanuelthiel,
Thanks for your comment,I have updated the Nuget Package to version 8.0 and it works fine.
