### ISSUE TITLE
Commands doesn't work on TouchUp Down or clicked

### ISSUE THREAD

**Issue by clovs** [robinmanuelthiel/flexbutton#6]
hello,

I notice that Binding Commands doesn't work on TouchUp Down or clicked.

Thanks for your great work!

**Comment by robinmanuelthiel** [comment]
Yep, will add support for that in upcoming releases. Feel free to add a PR for this if you can't wait. Should just be a few lines of code

**Comment by robinmanuelthiel** [comment]
In the meantime, you can use [Behaviors](https://developer.xamarin.com/guides/xamarin-forms/application-fundamentals/behaviors/reusable/event-to-command-behavior/) to fire Commands from events. I like to recommend https://github.com/corradocavalli/Corcav.Behaviors for that.

**Comment by clovs** [comment]
Thanks :)

**Comment by robinmanuelthiel** [comment]
Latest version 0.4.0 fixes this. The `FlexButton` control now has bindable commands!
https://www.nuget.org/packages/Forms.Controls.FlexButton

**Comment by clovs** [comment]
Definitely thanks 👍
