### ISSUE TITLE
Clicked event triggered even when dragged outside

### ISSUE THREAD

**Issue by mhouSK** [robinmanuelthiel/flexbutton#63]
**Describe the bug**
When clicking on a FlexButton, the Clicked event is triggered even if the user drags its finger outside the button to cancel the action.

**To Reproduce**
1. Create a simple FlexButton and implement the Clicked event.
2. Click on the button and drag outside its frame. Release.
3. The Clicked event is triggered.

**Expected behavior**
The Clicked event should not be triggered.

**Please complete the following information:**
- Which version of the FlexButton do you use? 0.8.0
- Which version of Xamarin.Forms do you use? 3.1.0
- Which OS are you talking about? Android 8.1, iOS 11.4

**Comment by robinmanuelthiel** [comment]
Interesting. Would you still expect the `TouchedUp` to get triggered? I would say yes, right?

**Comment by mhouSK** [comment]
I would say that TouchedDown is triggered because the user pressed on the button, but TouchedUp is not because the user left the button before removing its finger.

Clicked should only be triggered in case of a TouchUpInside (finger released inside the bounds of the button after a TouchDown of this same button).

Thanks for your help!

**Comment by robinmanuelthiel** [comment]
Maybe we should introduce events like `TouchedDownInside`, `TouchedUpOutside` and so on. Then everyone can decide what fits his or her needs.

**Comment by gaffkins** [comment]
Hi. It's any chance to update?

**Comment by robinmanuelthiel** [comment]
After years, I finally found the time to work on that project again. With the 0.12.0 release, this should be fixed.
