### ISSUE TITLE
[UWP] In Release Mode the button is not clickable

### ISSUE THREAD

**Issue by Agredo** [robinmanuelthiel/flexbutton#64]
In Release Mode the button is not clickable in FlexButton v. 0.8.

**Comment by robinmanuelthiel** [comment]
Cannot reproduce with the provided information. Tested the Demo project from this repository. Please use the [ISSUE TEMPLATE](https://github.com/robinmanuelthiel/flexbutton/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), when filing bugs. Can you please provide more information?

**Comment by Jamesmallon1** [comment]
@robinmanuelthiel issue is reproducible when Native .NET Toolchain is enabled in release mode. Probably worth mentioning in your documentation on UWP there is an extra step where by if you are going to enable this option, you must do the following on initialising Xamarin.Forms:

```
 var rendererAssemblies = new[]
            {
                typeof(Flex.UWP.CustomRenderers.GestureFrameRenderer).GetTypeInfo().Assembly,
            };

            Xamarin.Forms.Forms.Init(args, rendererAssemblies);
```

Thanks for a great plugin.

**Comment by sshary019** [comment]
I experienced the button control was not working on release mode in my app so I was kinda worried and because of that, I couldn't release my app on Windows Store. Now I got the solution for what I was looking for. The control is really amazing. Kudos :)
