### ISSUE TITLE
on Android: System.MissingMethodException: Default constructor not found for type Flex.Android.Effects.ColorOverlayEffectAndroid

### ISSUE THREAD

**Issue by jrgsc** [robinmanuelthiel/flexbutton#66]
**Describe the bug**
When loading form with the control, error appears:
System.MissingMethodException: Default constructor not found for type Flex.Android.Effects.ColorOverlayEffectAndroid

**To Reproduce**
Installed on nuget, added button from code behind.

**Expected behavior**
Render buttons.

**Please complete the following information:**
- Which version of the FlexButton do you use? -- 0.8
- Which version of Xamarin.Forms do you use? -- 3.3.0.912540
- Which OS are you talking about? -- Android

**Comment by robinmanuelthiel** [comment]
Oh, interesting. What are your Linker settings?

**Comment by robinmanuelthiel** [comment]
Would you please share you code-behind snipped for creating the button or (even better) a sample project?
