### ISSUE TITLE
how to use flex button with command parameter 

### ISSUE THREAD

**Issue by ronakshethia** [robinmanuelthiel/flexbutton#71]
i am trying to send value in command parameter to get it in my clicked binding of viewmodel 
something like this [](https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/commanding#using-command-parameters) [https://docs.microsoft.com/en-us/xamarin/xamarin-forms/app-fundamentals/data-binding/commanding#using-command-parameters](url)

whenever i am doing this  ClickedCommandParameter="1"  my button get disabled could u please help me how can i get the command parameter value in viewmodel

**Comment by fjuzen** [comment]
What was the solution for this problem?

**Comment by qz2rg4** [comment]
Hi I am facing the same problem. Please advise

**Comment by qz2rg4** [comment]
Update-- I managed to rectify the problem by setting the binding context in the ContentPage constructor
