### ISSUE TITLE
Setting Icon throwing System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by LeoJHarris** [robinmanuelthiel/flexbutton#73]
Hi, I seem to be getting a System.NullReferenceException: Object reference not set to an instance of an object. when I set the Icon on the flexButton, I can confirm the image exists and is in my drawable folders called shopping_cart_white.png

```csharp
<controls:FlexButton
                    BackgroundColor="{StaticResource XeniaRedThemeColor}"
                    BorderColor="White"
                    BorderThickness="2"
                    CornerRadius="40"
                    FontFamily="{StaticResource RegularFont}"
                    FontSize="{StaticResource SubHeader}"
                    ForegroundColor="White"
                    HeightRequest="80"
                    HorizontalOptions="End"
                    Icon="shopping_cart_white.png"
                    Text="Shopping Cart"
                    VerticalOptions="Center"
                    WidthRequest="120" />
```

![Capture](https://user-images.githubusercontent.com/5468757/55112706-0aa83d00-5142-11e9-8b2f-d56d0ef692e8.PNG)

When I remove the line `Icon="shopping_cart_white.png"` the null pointer issue goes away, any ideas please??

**Comment by LeoJHarris** [comment]
See stack trace attached:

[exception.txt](https://github.com/robinmanuelthiel/flexbutton/files/3015333/exception.txt)

**Comment by LeoJHarris** [comment]
No body else having this issue?

**Comment by Kelve17** [comment]
Hi. Did u manage to solve it ?

**Comment by robinmanuelthiel** [comment]
Can you please confirm that this is still happening after updating to version 0.10.0? Should work with version 0.10.0. https://www.nuget.org/packages/Forms.Controls.FlexButton/0.10.0
