### ISSUE TITLE
Not working on Xamarin.Forms 4.0.0

### ISSUE THREAD

**Issue by FruTech** [robinmanuelthiel/flexbutton#79]
Was working fine on forms 3.6 but updating my forms to 4.0.0 totally crashed the app due to flexButton control

**Comment by robinmanuelthiel** [comment]
Hey @FruTech, which OS are we talking about? Can you please use the Issue Template next time?

**Comment by robinmanuelthiel** [comment]
Should work with version 0.10.0. https://www.nuget.org/packages/Forms.Controls.FlexButton/0.10.0
