### ISSUE TITLE
not fire ClickedCommand or TouchedUpCommand

### ISSUE THREAD

**Issue by lolohouse** [robinmanuelthiel/flexbutton#82]
Not fire command ni TouchedUp  ni clicked

**To Reproduce**
xaml:
<flex:FlexButton Text="ENTRAR"
            Grid.Row="4"
            Grid.Column="1"
            Padding="16"
            FontSize="12"
            IsEnabled="true"
            IsToggled="true"
            ToggleMode="false"
            ClickedCommand="{Binding EnterCommand}"
            TouchedUpCommand="{Binding EnterCommand}"  />

**Expected behavior**

**Screenshots**

**Please complete the following information:**
- Which version of the FlexButton do you use? 0.11.0
- Which version of Xamarin.Forms do you use? 4.1
- Which OS are you talking about? 12

**Comment by robinmanuelthiel** [comment]
I can't reproduce your issue. Copied your code to a test project and everything works as expected. Please note, that using `ClickedCommand` **AND** `TouchedUpCommand` will fire the Comamnd twice, as both events fill be fired on a click.

Also, there is no point in setting `ToggleMode` to `false` and `IsToggled` to `true`.

**Comment by lolohouse** [comment]
Sorry, my job has not left me, prepare a test project ..
I annex it now.
[lolo.zip](https://github.com/robinmanuelthiel/flexbutton/files/3416168/lolo.zip)
