### ISSUE TITLE
FlexButton won't work on iOS when using it on Xamarin Forms Project

### ISSUE THREAD

**Issue by Farshid1723** [robinmanuelthiel/flexbutton#83]
Hi,
I have been busy with this issue since last two weeks and I couldn't find the issue root cause.
flexButton sample project works well on all platforms, But whenever I have added it from Nugget into my solution, It just works well on Android Platform. I mean that all buttons are working the way excepted, But the same code doesn't work on iOS. As I checked several times, OnClick event and assigned ICommand properties didn't raised on iOS side, while they are working like charm on Android. Is there any issue from my code? Did I forget to do something for iOS project?

**Comment by Farshid1723** [comment]
[FlexDemo.zip](https://github.com/robinmanuelthiel/flexbutton/files/3563094/FlexDemo.zip)

**Comment by Farshid1723** [comment]
This is my sample solution for using FlexButton on Xamarin Forms.

**Comment by Farshid1723** [comment]
This is all the code that is working on Android but not working on iOS.

**Comment by robinmanuelthiel** [comment]
Do you call `FlexButton.Init();` as [shown in the docs](https://github.com/robinmanuelthiel/flexbutton#how-to-use)?

**Comment by Farshid1723** [comment]
No, I didn't aware of that piece of code! Thanks, It solved my issue.
