### ISSUE TITLE
A few suggestions

### ISSUE THREAD

**Issue by IeuanWalker** [robinmanuelthiel/flexbutton#84]
I have created the following fork - 
https://github.com/IeuanWalker/Xamarin.Forms.FlexButton

I created this because our designers needed different features, which where - 

- Use font icons instead of images _(do want to look into using FontImageSource , to allow FontImageSource, embedded resources, files, and URIs. But wasn't to sure how to implement this - https://devblogs.microsoft.com/xamarin/introducing-xamarin-forms-4-0-the-era-of-shell/)_
- Icons either side of the text
- Be able to move the icons and text as they wish

In doing so I noticed a few things that could be changed -
- The IconOrientation could be removed and use FlexDirection directly
- Could also remove icon padding logic based on IconOrientation, allow the user to add there own logic
- No need to handle the icon and text using a grid, I ended up replacing this with FlexBasis
```csharp
FlexLayout.SetBasis(ButtonText, string.IsNullOrEmpty(Text) ?
    new FlexBasis(0, false) :
    FlexBasis.Auto);
```
- Instead of using the Xamarin.Forms frame as the base for the GestureFrame, I used PancakeView and then exposed a few of the pancakeview properties
- Added a property to allow the user to control the `JustifyContent` of the flexlayout
- Added `FlexLayout.Grow` and `HorizontalTextAlignment` to allow complete control of the placement of the different items within the button

Here is what I am now able to do with FlexButton -
![image](https://user-images.githubusercontent.com/6544051/64877126-a5d99400-d648-11e9-9ced-6fb7e7517cfc.png)

Most of the changes I made are braking changes that's why I havnt created a pull request.
But if you do want me to add or update anything let me know.
Hope this was useful :)

**Comment by magnusblb** [comment]
I have a case where the `HorizontalTextAlignment` property would be very useful.

**Comment by IeuanWalker** [comment]
@magnusblb I am in the middle of creating my own control that gives complete control to the content of the button, ill update you once a beta is ready. Not sure when that will be though.

**Comment by robinmanuelthiel** [comment]
Thanks for all the suggestions. Some of them like the Font icons (#1) have found their way into new and existing issues. For the other suggestions, I would highly welcome contributions and PRs!

**Comment by IeuanWalker** [comment]
@magnusblb should check out my new control - https://github.com/IeuanWalker/Xamarin.Forms.StateButton
