### ISSUE TITLE
【bug】focus status changed when clicked the flexbutton

### ISSUE THREAD

**Issue by 632575987** [robinmanuelthiel/flexbutton#85]
when I clicked the flexbutton, the first Entry or Editor control of the page focused. so confused.

I think the correct logic is that the focus state remains the same after the flexbutton released.

I tested it on UWP platform.

I need help ~~~~😀😀😀

**Comment by 632575987** [comment]
Another problem is that icon didnt shown Occasionally. (I setted the icon property only , sometimes it doesn't shown,  sometimes it works well.)

**Comment by robinmanuelthiel** [comment]
I can't reproduce your issue, so can you please provide a sample or at least repro steps?
