### ISSUE TITLE
[Android] TouchedDownCommand NullReferenceException

### ISSUE THREAD

**Issue by fgbustoa** [robinmanuelthiel/flexbutton#87]
**Describe the bug**
If i set a TouchedDownCommand property in XAML, i then receive a NullReferenceException. Someone already mentioned this problem in UWP. Also Android is affected

TouchedUpCommand is OK, and is correctly fired

**To Reproduce**
*Steps to reproduce the behavior:*

<flex:FlexButton
            BackgroundColor="Blue"
            CornerRadius="24"
            ForegroundColor="White"
            HeightRequest="48"
            HorizontalOptions="Center"
            Icon="recorder.png"
            IsVisible="True"
            TouchedDownCommand="{Binding StartRecordingCommand}"
            TouchedUpCommand="{Binding StopRecordingCommand}"
            VerticalOptions="Center"
            WidthRequest="48" />

**Expected behavior**
Handle the 2 commands

**Please complete the following information:**
- Which version of the FlexButton do you use? 0.11.0
- Which version of Xamarin.Forms do you use? 4.5
- Which OS are you talking about? Android

**Comment by robinmanuelthiel** [comment]
Can confirm. I finally got time to work on that project again, so it will hopefully be fixed over the holidays.
