### ISSUE TITLE
Icon isssues

### ISSUE THREAD

**Issue by IeuanWalker** [robinmanuelthiel/flexbutton#9]
Control version: 0.4.0

Hi, great control I just have 2 issues.

1. Is there going to be an update to allow SVG as an icon?
1. Is there a way to change the default position of the icon with text
i.e. at the moment it defaults to the left of the text but we need it on the right.

**Comment by robinmanuelthiel** [comment]
Good catch, thanks for the feedback. Will look into options for that and add it to my backlog. Icon position totally makes sense and shouldn't be too hard to implement. SVGs will be more work but I was already thinking of switching over to SkiaSharp, so let's see...

**Comment by IeuanWalker** [comment]
@robinmanuelthiel Great that's awesome, thanks.

**Comment by Depechie** [comment]
Added the orientation in Pull https://github.com/robinmanuelthiel/flexbutton/pull/14
No SVG yet :)

**Comment by robinmanuelthiel** [comment]
Awesome work, thanks a lot for all your contributions! Will add you as a contributor on the welcome page!

**Comment by robinmanuelthiel** [comment]
Fixed in latest 0.5.0 Release
