### ISSUE TITLE
Click event is called repeatedly when using flexbutton inside a TitleView

### ISSUE THREAD

**Issue by fun-works** [robinmanuelthiel/flexbutton#92]
**Describe the bug**
Click event is called repeatedly when using flexbutton inside a TitleView

**To Reproduce**
*Steps to reproduce the behavior:*

**Expected behavior**
*A clear and concise description of what you expected to happen.*

**Screenshots**

Page XAML:
```
...
    <NavigationPage.TitleView>
        <StackLayout Orientation="Horizontal" 
                     Spacing="0" 
                     VerticalOptions="Fill" 
                     HorizontalOptions="FillAndExpand" BackgroundColor="{DynamicResource ColorBackgroundButtonMenu}">

            <flex:FlexButton 
                    Icon="alarm.png"
                    Clicked="Alarm_Clicked"
                    >
            </flex:FlexButton>

...
```

Button Click event:
```
 private void Alarm_Clicked(object sender, EventArgs e)
        {
            Navigation.PushAsync(new Schedule(schedules));
        }
```

**Please complete the following information:**
- Which version of the FlexButton do you use? -> 0.11.0
- Which version of Xamarin.Forms do you use? -> 4.7.0.968
- Which OS are you talking about? -> Android

**Comment by robinmanuelthiel** [comment]
I gave it a try and can't reproduce the issue. When counting up a number, the counter only gets increased by one for me, even when putting the FlexButton into a NavigationPage.TitleView. Can you share a sample project?
